id = "cyan-light-theme"
name = "Cyan Light Theme"
version = "0.7.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Port of the Cyan Light Theme from the JetBrains Marketplace"
repository = "https://github.com/biaqat/cyan-light-theme-zed"
