id = "cyan-light-theme"
name = "Cyan Light Theme"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Cyan Light theme for Zed"
repository = "https://github.com/biaqat/cyan-light-theme-zed"